name: unisyft_web_dev_local

services:
  laasa_web_dev_local:
    image: postgres:18
    container_name: unisyft_web_dev_local
    ports:
      - "127.0.0.1:5440:5432"
    environment:
      POSTGRES_USER: unisyft_web_dev_local
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: unisyft_web_dev_local
    volumes:
      - unisyft_web_dev_local_data:/var/lib/postgresql
    restart: unless-stopped
  
volumes:
  unisyft_web_dev_local_data:
